### ISSUE TITLE
Full CAN Frame Fields

### ISSUE THREAD

**Issue by alexyoung97** [danielbk18/gocan#1]
Hi,

Thanks for making this project, it's great! However I was looking at the CAN frame in the CAN specification and the CAN frame struct in the code for comparison. It seems to include these fields:

Id uint32
Rtr bool
Dlc uint8
Data uint64
TimeStamp time.Time

Do you have any reasons for not including the other bit fields in the CAN frame specification? They are not as interesting from a data point of view but may be useful for simulation. These are:

Start of frame (SOF)
Identifier Extension (IDE)
Reserved bit (r0) for possible future use
Cyclic redundancy check (CRC)
Acknowledgement (ACK)
End of frame (EOF)
Interframe space (IFS).

Thanks,

Alex

**Comment by danielbk18** [comment]
Hi Alex, thanks for commenting. 

I've developed this as a base to use in a J1939 simulation, which I stopped along the way, as it is incomplete I didn't publish it. I was interested in mapping the behavior of the messages, specially when using several frames to transmit messages over 8 bytes (using the transport protocol), and bus load. So, considering this point of view, as you mentioned these fields were not interesting data, since I would just add the ammount of bits in the end to simulate bus usage, and avoid the repetition of information everytime I created a new frame.

Feel free to add them if it helps your project, to me they didn't make sense at the time so I just ignored these fields. If you have any other doubts I'd be glad to help.

thanks,
Daniel.
